export const STATES = [
  "Andaman & Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "D&N Haveli and Daman & Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
] as const;

export type State = typeof STATES[number];

export const CATEGORIES = [
  "Total IPC Crimes",
  "Total SLL Crimes",
  "Crime Against Women",
  "Crime Against Children",
  "Crime Against Scheduled Castes",
  "Crime Against Scheduled Tribes",
  "Crime Against Senior Citizens",
  "Cyber Crimes",
  "Economic Offences",
  "NDPS Act",
  "Missing Persons",
  "Juveniles in IPC Crimes",
  "Juveniles in SLL Crimes",
  "Property Stolen & Recovered",
  "Human Trafficking",
  "Environment Related Offences",
  "Crimes by Foreigners",
  "Police Disposal",
  "Seizures",
  "Cases Registered"
] as const;

export type Category = typeof CATEGORIES[number];
