[build]
  base = "packages/playground"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://api.bharatdata.dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"
