"""
Manifest Generator (Phase 8: Human-in-the-Loop Nazar Check)
-----------------------------------------------------------
Consumes the JSON mappings generated by discovery engines,
and generates a professional, formatted Excel manifest.
"""

import os
import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any
import pandas as pd
from loguru import logger
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.worksheet.page import PageMargins

class ManifestGenerator:
    """
    Generates a professionally formatted Excel manifest from discovery results.
    """
    def __init__(self, definition: Dict[str, Any]):
        self.definition = definition
        self.dataset_id = definition["identity"]["id"]
        self.project_root = Path(__file__).resolve().parents[2]
        self.manifest_dir = self.project_root / "pipeline" / "manifests"
        self.manifest_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, resource_map: Dict[str, str]):
        """
        Generates the Excel manifest from a resource mapping dictionary.
        """
        logger.info(f"Generating manifest for {len(resource_map)} entities.")

        rows = []
        for entity, resource_id in resource_map.items():
            rows.append({
                "entity_name": entity,
                "resource_id": resource_id,
                "is_verified": "FALSE",  # Strict default
                "status": "pending",
                "record_count": "",
                "last_updated": ""
            })

        df = pd.DataFrame(rows)
        manifest_file = self.manifest_dir / f"{self.dataset_id}_manifest.xlsx"
        
        with pd.ExcelWriter(str(manifest_file), engine='openpyxl') as writer:
            df.to_excel(writer, index=False, sheet_name="Ingestion_Manifest")
            
            workbook = writer.book
            worksheet = writer.sheets["Ingestion_Manifest"]
            
            header_font = Font(bold=True, color="FFFFFF")
            header_fill = PatternFill(start_color="111827", end_color="111827", fill_type="solid")
            header_alignment = Alignment(horizontal="center", vertical="center")
            
            for col_num, cell in enumerate(worksheet[1], 1):
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = header_alignment
                
                column_letter = openpyxl.utils.get_column_letter(col_num)
                if cell.value == "resource_id":
                    worksheet.column_dimensions[column_letter].width = 40
                elif cell.value == "entity_name":
                    worksheet.column_dimensions[column_letter].width = 30
                elif cell.value == "is_verified":
                    worksheet.column_dimensions[column_letter].width = 15
                else:
                    worksheet.column_dimensions[column_letter].width = 18

            worksheet.freeze_panes = "A2"
            
            today_date = datetime.now().strftime("%Y-%m-%d")
            worksheet.oddHeader.left.text = f"Date: {today_date}"
            worksheet.oddHeader.center.text = "&B&14BharatData Ingestion Manifest"
            worksheet.oddHeader.right.text = f"Dataset: {self.dataset_id}"
            worksheet.oddFooter.center.text = "Page &P of &N"
            worksheet.page_margins = PageMargins(left=0.5, right=0.5, top=0.75, bottom=0.75, header=0.3, footer=0.3)

        logger.success(f"Successfully generated formatted manifest: {manifest_file}")
        logger.info("ACTION REQUIRED: Open manifest, verify Resource IDs, and set is_verified = TRUE.")
