import json
import subprocess
import pandas as pd
from pathlib import Path
from loguru import logger

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DISTRICT_JSON = PROJECT_ROOT / "pipeline" / "resources" / "census_2011_districts.json"
MANIFEST_DIR = PROJECT_ROOT / "pipeline" / "manifests"

def get_all_states():
    with open(DISTRICT_JSON, 'r', encoding='utf-8') as f:
        data = json.load(f)
    return sorted(list(data.keys()))

def run_state_discovery(state):
    logger.info(f">>> Starting discovery for: {state}")
    cmd = [
        "python",
        "pipeline/discovery/async_slug_prober.py",
        "--state", state
    ]
    try:
        subprocess.run(cmd, check=True)
        return True
    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to discover {state}: {e}")
        return False

def consolidate_manifests():
    logger.info("Consolidating state manifests...")
    all_dfs = []
    
    # Pattern for state files generated by async_slug_prober
    for file in MANIFEST_DIR.glob("*_async_slug_results.xlsx"):
        if file.name == "national_async_slug_results.xlsx":
            continue
        logger.info(f"Reading {file.name}")
        df = pd.read_excel(file)
        all_dfs.append(df)
    
    if all_dfs:
        final_df = pd.concat(all_dfs, ignore_index=True)
        output_path = MANIFEST_DIR / "census_2011_pca_national_manifest.xlsx"
        final_df.to_excel(output_path, index=False)
        logger.success(f"Successfully created national manifest: {output_path}")
        logger.info(f"Total resources mapped: {len(final_df[final_df.status == 'OK'])}")
    else:
        logger.warning("No state manifests found to consolidate.")

if __name__ == "__main__":
    states = get_all_states()
    logger.info(f"Found {len(states)} states. Beginning sequential discovery...")
    
    for state in states:
        run_state_discovery(state)
        # We don't need to sleep here because async_slug_prober already has internal logic
        # and sequential state processing inherently reduces burst load.
        
    consolidate_manifests()
